version: "3.7"

services:
  db_entregas:
    image: postgres
    container_name: db_entregas
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma_delivery
    volumes:
      - pgdata_entregas:/var/lib/postgresql/data

  app:
    build: .
    container_name: entregas
    links:
      - db_entregas
    depends_on:
      - db_entregas
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    environment:
      DATABASE_URL: postgresql://admin:admin@db_entregas:5432/prisma_delivery

volumes:
  pgdata_entregas:
    driver: local

# docker-compose up --force-recreate -d
# docker logs rentalx -f
